{
  "hash": "e67994f2e1149480fd556fe58848aaaa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Nutrients vs fungal diversity by disease group (Spearman)\"\ndescription: \"Spearman correlations between dietary nutrients and alpha diversity, overall and stratified by study group (Active IBD, Quiescent, Non-IBD).\"\ndate: 2026-05-29\ncategories: [pre-specified, alpha-diversity, diet, nutrients]\nauthor: \"IBD Capstone team\"\n---\n\n## Research question\n\nAre certain **nutrients** associated with **fungal alpha diversity**, and do those associations **differ across disease groups**?\n\n**Null (overall):** No monotonic association between each nutrient and each alpha diversity metric across all samples.\n\n**Null (stratified):** Within each study group, no monotonic association between nutrient intake and alpha diversity.\n\nComparing **overall vs group-specific** Spearman \\(\\rho\\) is exploratory (small n per group); formal tests of correlation differences were not run.\n\n## Data\n\n| Role | Source |\n|------|--------|\n| Mycobiome (alpha) | `data/intermediate/alpha_long.rds` (`make wrangle`) |\n| Diet | `data/processed/dietary_cleaned.xlsx` (`make dietary` on `data/raw/OPT_dietary data(ALL).csv`) |\n| Disease group | `Study_group_new` on mycobiome metadata (from `OPT_MBI sample IDs meta.xlsx`) |\n\n- **Unit of analysis:** Stool sample (22 samples, 12 participants); nutrients are **participant means** across diet diary days (same as `merge_files.R`).\n- **Join key:** `Participant_ID` = `Participant ID (ESHA ID)` (normalized OPT codes).\n- **Nutrients:** Pre-specified panel (fiber, tryptophan, calories, sweeteners, sugars, fats, omegas, vitamin D, folate); see helpers.\n- **Inclusion:** Samples retained after `02_data_wrangling.R` removals.\n\n\n\n**Coverage:** 16 samples, 12 participants, 16 samples with fiber data; study groups: Active IBD, Non-IBD, Quiescent.\n\n## Methods\n\n| Item | Choice |\n|------|--------|\n| Test | Spearman rank correlation (`cor.test`, `method = \"spearman\"`) |\n| Response | Shannon, Simpson, Chao1 |\n| Predictors | Participant-mean nutrient intake (g, kcal, mg as recorded) |\n| Stratification | `Study_group_new` (Active IBD, Quiescent, Non-IBD) + **Overall** |\n| Multiple testing | Benjamini–Hochberg within each stratum (across nutrient × metric pairs) |\n| Minimum n | Correlation only if ≥ 4 complete pairs |\n| Significance | α = 0.05 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspearman_results <- spearman_nutrient_alpha(sample_nutrients)\n```\n:::\n\n\n## Assumptions and diagnostics\n\n- **Independence:** Up to two stool replicates per participant; dietary intake is duplicated across replicates. Exploratory only.\n- **Spearman:** Monotonic association; no linearity assumption.\n- **Stratified n:** Few samples per study group limits power; many strata will return `NA` correlations.\n\n## Results\n\n### Overall correlations\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Nutrient                       |Alpha metric |  n| Spearman rho|      p| BH-adjusted p|\n|:------------------------------|:------------|--:|------------:|------:|-------------:|\n|Total fiber (g/day)            |Shannon      | 16|       0.0000| 1.0000|        1.0000|\n|Total fiber (g/day)            |Simpson      | 16|      -0.0605| 0.8239|        0.9376|\n|Total fiber (g/day)            |Chao1        | 16|       0.1932| 0.4734|        0.9376|\n|Tryptophan (g/day)             |Shannon      | 16|      -0.2330| 0.3851|        0.9376|\n|Tryptophan (g/day)             |Simpson      | 16|      -0.0723| 0.7903|        0.9376|\n|Tryptophan (g/day)             |Chao1        | 16|       0.0723| 0.7903|        0.9376|\n|Calories (kcal/day)            |Shannon      | 16|       0.0354| 0.8964|        0.9644|\n|Calories (kcal/day)            |Simpson      | 16|      -0.1431| 0.5971|        0.9376|\n|Calories (kcal/day)            |Chao1        | 16|      -0.0752| 0.7819|        0.9376|\n|Artificial sweeteners (mg/day) |Shannon      | 16|       0.0973| 0.7199|        0.9376|\n|Artificial sweeteners (mg/day) |Simpson      | 16|       0.0310| 0.9093|        0.9644|\n|Artificial sweeteners (mg/day) |Chao1        | 16|      -0.1136| 0.6754|        0.9376|\n|Sugar (g/day)                  |Shannon      | 16|       0.1298| 0.6319|        0.9376|\n|Sugar (g/day)                  |Simpson      | 16|       0.2286| 0.3944|        0.9376|\n|Sugar (g/day)                  |Chao1        | 16|       0.2168| 0.4199|        0.9376|\n|Added sugar (g/day)            |Shannon      | 16|      -0.5339| 0.0331|        0.9376|\n|Added sugar (g/day)            |Simpson      | 16|       0.1903| 0.4803|        0.9376|\n|Added sugar (g/day)            |Chao1        | 16|      -0.1519| 0.5744|        0.9376|\n|Fat (g/day)                    |Shannon      | 16|      -0.3864| 0.1393|        0.9376|\n|Fat (g/day)                    |Simpson      | 16|       0.1932| 0.4734|        0.9376|\n|Fat (g/day)                    |Chao1        | 16|      -0.1755| 0.5156|        0.9376|\n|Omega-3 (g/day)                |Shannon      | 16|       0.0885| 0.7445|        0.9376|\n|Omega-3 (g/day)                |Simpson      | 16|      -0.0693| 0.7986|        0.9376|\n|Omega-3 (g/day)                |Chao1        | 16|      -0.1726| 0.5228|        0.9376|\n|Omega-6 (g/day)                |Shannon      | 16|      -0.3363| 0.2028|        0.9376|\n|Omega-6 (g/day)                |Simpson      | 16|      -0.1932| 0.4734|        0.9376|\n|Omega-6 (g/day)                |Chao1        | 16|       0.1637| 0.5446|        0.9376|\n|Vitamin D (mcg/day)            |Shannon      | 16|       0.4690| 0.0668|        0.9376|\n|Vitamin D (mcg/day)            |Simpson      | 16|      -0.0929| 0.7321|        0.9376|\n|Vitamin D (mcg/day)            |Chao1        | 16|      -0.0929| 0.7321|        0.9376|\n|Folate (mcg/day)               |Shannon      | 16|       0.1681| 0.5336|        0.9376|\n|Folate (mcg/day)               |Simpson      | 16|       0.0221| 0.9352|        0.9644|\n|Folate (mcg/day)               |Chao1        | 16|      -0.1578| 0.5594|        0.9376|\n\n\n:::\n:::\n\n\n### Stratified by study group\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Study group |Nutrient                       |Alpha metric |  n| Spearman rho|      p| BH-adjusted p|\n|:-----------|:------------------------------|:------------|--:|------------:|------:|-------------:|\n|Active IBD  |Total fiber (g/day)            |Shannon      |  6|       0.1471| 0.7809|        0.8951|\n|Active IBD  |Total fiber (g/day)            |Simpson      |  6|       0.0883| 0.8679|        0.8951|\n|Active IBD  |Total fiber (g/day)            |Chao1        |  6|      -0.0883| 0.8679|        0.8951|\n|Active IBD  |Tryptophan (g/day)             |Shannon      |  6|      -0.2648| 0.6121|        0.8951|\n|Active IBD  |Tryptophan (g/day)             |Simpson      |  6|       0.0883| 0.8679|        0.8951|\n|Active IBD  |Tryptophan (g/day)             |Chao1        |  6|       0.2648| 0.6121|        0.8951|\n|Active IBD  |Calories (kcal/day)            |Shannon      |  6|       0.5591| 0.2488|        0.8951|\n|Active IBD  |Calories (kcal/day)            |Simpson      |  6|      -0.4414| 0.3809|        0.8951|\n|Active IBD  |Calories (kcal/day)            |Chao1        |  6|      -0.8533| 0.0307|        0.5065|\n|Active IBD  |Artificial sweeteners (mg/day) |Shannon      |  6|      -0.6179| 0.1911|        0.8951|\n|Active IBD  |Artificial sweeteners (mg/day) |Simpson      |  6|       0.0883| 0.8679|        0.8951|\n|Active IBD  |Artificial sweeteners (mg/day) |Chao1        |  6|       0.6179| 0.1911|        0.8951|\n|Active IBD  |Sugar (g/day)                  |Shannon      |  6|      -0.5591| 0.2488|        0.8951|\n|Active IBD  |Sugar (g/day)                  |Simpson      |  6|       0.4414| 0.3809|        0.8951|\n|Active IBD  |Sugar (g/day)                  |Chao1        |  6|       0.8533| 0.0307|        0.5065|\n|Active IBD  |Added sugar (g/day)            |Shannon      |  6|      -0.1471| 0.7809|        0.8951|\n|Active IBD  |Added sugar (g/day)            |Simpson      |  6|      -0.4414| 0.3809|        0.8951|\n|Active IBD  |Added sugar (g/day)            |Chao1        |  6|      -0.2648| 0.6121|        0.8951|\n|Active IBD  |Fat (g/day)                    |Shannon      |  6|       0.1471| 0.7809|        0.8951|\n|Active IBD  |Fat (g/day)                    |Simpson      |  6|       0.0883| 0.8679|        0.8951|\n|Active IBD  |Fat (g/day)                    |Chao1        |  6|      -0.0883| 0.8679|        0.8951|\n|Active IBD  |Omega-3 (g/day)                |Shannon      |  6|      -0.0883| 0.8679|        0.8951|\n|Active IBD  |Omega-3 (g/day)                |Simpson      |  6|      -0.4414| 0.3809|        0.8951|\n|Active IBD  |Omega-3 (g/day)                |Chao1        |  6|      -0.2648| 0.6121|        0.8951|\n|Active IBD  |Omega-6 (g/day)                |Shannon      |  6|      -0.1471| 0.7809|        0.8951|\n|Active IBD  |Omega-6 (g/day)                |Simpson      |  6|      -0.4414| 0.3809|        0.8951|\n|Active IBD  |Omega-6 (g/day)                |Chao1        |  6|      -0.2648| 0.6121|        0.8951|\n|Active IBD  |Vitamin D (mcg/day)            |Shannon      |  6|      -0.1471| 0.7809|        0.8951|\n|Active IBD  |Vitamin D (mcg/day)            |Simpson      |  6|      -0.0883| 0.8679|        0.8951|\n|Active IBD  |Vitamin D (mcg/day)            |Chao1        |  6|       0.0883| 0.8679|        0.8951|\n|Active IBD  |Folate (mcg/day)               |Shannon      |  6|       0.3237| 0.5314|        0.8951|\n|Active IBD  |Folate (mcg/day)               |Simpson      |  6|       0.2648| 0.6121|        0.8951|\n|Active IBD  |Folate (mcg/day)               |Chao1        |  6|      -0.0294| 0.9559|        0.9559|\n|Non-IBD     |Total fiber (g/day)            |Shannon      |  5|      -0.5643| 0.3217|        0.7016|\n|Non-IBD     |Total fiber (g/day)            |Simpson      |  5|      -0.0513| 0.9347|        0.9347|\n|Non-IBD     |Total fiber (g/day)            |Chao1        |  5|       0.6669| 0.2189|        0.6020|\n|Non-IBD     |Tryptophan (g/day)             |Shannon      |  5|       0.1539| 0.8048|        0.9347|\n|Non-IBD     |Tryptophan (g/day)             |Simpson      |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Tryptophan (g/day)             |Chao1        |  5|       0.9747| 0.0048|        0.0530|\n|Non-IBD     |Calories (kcal/day)            |Shannon      |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Calories (kcal/day)            |Simpson      |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Calories (kcal/day)            |Chao1        |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Artificial sweeteners (mg/day) |Shannon      |  5|      -0.0513| 0.9347|        0.9347|\n|Non-IBD     |Artificial sweeteners (mg/day) |Simpson      |  5|      -0.0513| 0.9347|        0.9347|\n|Non-IBD     |Artificial sweeteners (mg/day) |Chao1        |  5|      -0.8721| 0.0539|        0.2539|\n|Non-IBD     |Sugar (g/day)                  |Shannon      |  5|       0.3591| 0.5528|        0.7016|\n|Non-IBD     |Sugar (g/day)                  |Simpson      |  5|       0.3591| 0.5528|        0.7016|\n|Non-IBD     |Sugar (g/day)                  |Chao1        |  5|       0.3591| 0.5528|        0.7016|\n|Non-IBD     |Added sugar (g/day)            |Shannon      |  5|      -0.6669| 0.2189|        0.6020|\n|Non-IBD     |Added sugar (g/day)            |Simpson      |  5|       0.8721| 0.0539|        0.2539|\n|Non-IBD     |Added sugar (g/day)            |Chao1        |  5|      -0.6669| 0.2189|        0.6020|\n|Non-IBD     |Fat (g/day)                    |Shannon      |  5|      -0.5643| 0.3217|        0.7016|\n|Non-IBD     |Fat (g/day)                    |Simpson      |  5|       0.9747| 0.0048|        0.0530|\n|Non-IBD     |Fat (g/day)                    |Chao1        |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Omega-3 (g/day)                |Shannon      |  5|      -0.0513| 0.9347|        0.9347|\n|Non-IBD     |Omega-3 (g/day)                |Simpson      |  5|      -0.0513| 0.9347|        0.9347|\n|Non-IBD     |Omega-3 (g/day)                |Chao1        |  5|      -0.8721| 0.0539|        0.2539|\n|Non-IBD     |Omega-6 (g/day)                |Shannon      |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Omega-6 (g/day)                |Simpson      |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Omega-6 (g/day)                |Chao1        |  5|      -0.3591| 0.5528|        0.7016|\n|Non-IBD     |Vitamin D (mcg/day)            |Shannon      |  5|       0.9747| 0.0048|        0.0530|\n|Non-IBD     |Vitamin D (mcg/day)            |Simpson      |  5|      -0.5643| 0.3217|        0.7016|\n|Non-IBD     |Vitamin D (mcg/day)            |Chao1        |  5|       0.1539| 0.8048|        0.9347|\n|Non-IBD     |Folate (mcg/day)               |Shannon      |  5|       0.6669| 0.2189|        0.6020|\n|Non-IBD     |Folate (mcg/day)               |Simpson      |  5|      -0.8721| 0.0539|        0.2539|\n|Non-IBD     |Folate (mcg/day)               |Chao1        |  5|       0.6669| 0.2189|        0.6020|\n|Quiescent   |Total fiber (g/day)            |Shannon      |  5|      -0.0513| 0.9347|        0.9347|\n|Quiescent   |Total fiber (g/day)            |Simpson      |  5|      -0.0513| 0.9347|        0.9347|\n|Quiescent   |Total fiber (g/day)            |Chao1        |  5|       0.4104| 0.4925|        0.7932|\n|Quiescent   |Tryptophan (g/day)             |Shannon      |  5|      -0.4617| 0.4338|        0.7932|\n|Quiescent   |Tryptophan (g/day)             |Simpson      |  5|      -0.1539| 0.8048|        0.9347|\n|Quiescent   |Tryptophan (g/day)             |Chao1        |  5|      -0.8208| 0.0886|        0.7308|\n|Quiescent   |Calories (kcal/day)            |Shannon      |  5|       0.4617| 0.4338|        0.7932|\n|Quiescent   |Calories (kcal/day)            |Simpson      |  5|      -0.0513| 0.9347|        0.9347|\n|Quiescent   |Calories (kcal/day)            |Chao1        |  5|       0.4104| 0.4925|        0.7932|\n|Quiescent   |Artificial sweeteners (mg/day) |Shannon      |  5|       0.5643| 0.3217|        0.7932|\n|Quiescent   |Artificial sweeteners (mg/day) |Simpson      |  5|       0.3591| 0.5528|        0.7932|\n|Quiescent   |Artificial sweeteners (mg/day) |Chao1        |  5|       0.2052| 0.7406|        0.9052|\n|Quiescent   |Sugar (g/day)                  |Shannon      |  5|       0.5643| 0.3217|        0.7932|\n|Quiescent   |Sugar (g/day)                  |Simpson      |  5|       0.3591| 0.5528|        0.7932|\n|Quiescent   |Sugar (g/day)                  |Chao1        |  5|       0.2052| 0.7406|        0.9052|\n|Quiescent   |Added sugar (g/day)            |Shannon      |  5|      -0.4617| 0.4338|        0.7932|\n|Quiescent   |Added sugar (g/day)            |Simpson      |  5|       0.0513| 0.9347|        0.9347|\n|Quiescent   |Added sugar (g/day)            |Chao1        |  5|      -0.4104| 0.4925|        0.7932|\n|Quiescent   |Fat (g/day)                    |Shannon      |  5|      -0.6669| 0.2189|        0.7932|\n|Quiescent   |Fat (g/day)                    |Simpson      |  5|      -0.8721| 0.0539|        0.7308|\n|Quiescent   |Fat (g/day)                    |Chao1        |  5|      -0.2052| 0.7406|        0.9052|\n|Quiescent   |Omega-3 (g/day)                |Shannon      |  5|       0.5643| 0.3217|        0.7932|\n|Quiescent   |Omega-3 (g/day)                |Simpson      |  5|       0.5643| 0.3217|        0.7932|\n|Quiescent   |Omega-3 (g/day)                |Chao1        |  5|       0.6156| 0.2690|        0.7932|\n|Quiescent   |Omega-6 (g/day)                |Shannon      |  5|      -0.4617| 0.4338|        0.7932|\n|Quiescent   |Omega-6 (g/day)                |Simpson      |  5|      -0.9747| 0.0048|        0.1590|\n|Quiescent   |Omega-6 (g/day)                |Chao1        |  5|       0.1026| 0.8696|        0.9347|\n|Quiescent   |Vitamin D (mcg/day)            |Shannon      |  5|       0.3591| 0.5528|        0.7932|\n|Quiescent   |Vitamin D (mcg/day)            |Simpson      |  5|       0.6669| 0.2189|        0.7932|\n|Quiescent   |Vitamin D (mcg/day)            |Chao1        |  5|       0.3078| 0.6144|        0.8448|\n|Quiescent   |Folate (mcg/day)               |Shannon      |  5|      -0.3591| 0.5528|        0.7932|\n|Quiescent   |Folate (mcg/day)               |Simpson      |  5|       0.3591| 0.5528|        0.7932|\n|Quiescent   |Folate (mcg/day)               |Chao1        |  5|      -0.8208| 0.0886|        0.7308|\n\n\n:::\n:::\n\n\n**No nutrient × diversity pairs were significant after BH adjustment (q < 0.05) in any stratum.**\n\n\n**Total fiber × Shannon (all strata):**\n\nOverall: rho = 0.000 (n = 16, p = 1.0000)\nActive IBD: rho = 0.147 (n = 6, p = 0.7809)\nNon-IBD: rho = -0.564 (n = 5, p = 0.3217)\nQuiescent: rho = -0.051 (n = 5, p = 0.9347)\n\n## Figures\n\n### Total fiber vs Shannon diversity (by study group)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_nutrient_alpha_scatter(\n  sample_nutrients,\n  nutrient_col = \"TotFib (g)\",\n  metric = \"Shannon\",\n  facet_by = \"Study_group_new\"\n)\n```\n\n::: {.cell-output-display}\n![Total fiber intake vs Shannon diversity. Points are stool samples; diet is participant-mean intake. Facets show study group.](index_files/figure-html/fig-fiber-shannon-1.png){#fig-fiber-shannon fig-align='center' width=768}\n:::\n:::\n\n\n### Tryptophan vs Shannon diversity (by study group)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_nutrient_alpha_scatter(\n  sample_nutrients,\n  nutrient_col = \"Trp (g)\",\n  metric = \"Shannon\",\n  facet_by = \"Study_group_new\"\n)\n```\n\n::: {.cell-output-display}\n![Tryptophan intake vs Shannon diversity, faceted by study group.](index_files/figure-html/fig-trp-shannon-1.png){#fig-trp-shannon fig-align='center' width=768}\n:::\n:::\n\n\n\n\n## Interpretation\n\nOverall Spearman correlations pool all study groups; **stratified** correlations describe associations within Active IBD, Quiescent, and Non-IBD separately. A nutrient may correlate with diversity overall but not within groups (or vice versa) when group-specific slopes differ or sample sizes are small.\n\nThese results do **not** test whether two correlation coefficients differ significantly between groups; that would require larger n or dedicated methods (e.g. comparing dependent correlations).\n\n## Reproducibility\n\n- **Helpers:** `stats/R/nutrient_association_helpers.R`\n- **Diet pipeline:** `src/diet/dietary.py`\n- **Merge reference:** `src/merge_files.R` (`aggregate_dietary`)\n- **Render:** `quarto render stats` from repository root\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}