{
  "hash": "f96ebd8020659b511b923cbcc1afac77",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PCA and clustering on combined diet and mycobiome profiles\"\ndescription: \"Participant-level PCA of scaled nutrient intake and genus relative abundance, with hierarchical clustering to explore diet–mycobiome groupings.\"\ndate: 2026-05-29\ncategories: [pre-specified, pca, clustering, diet, genus]\nauthor: \"IBD Capstone team\"\n---\n\n## Research question\n\nCan **participants** be grouped by combined **diet (nutrients)** and **mycobiome (genus taxa)** profiles?\n\n**Pre-specified method; exploratory interpretation:** with 12 participants, PCA and clustering describe patterns in the data but do not provide stable cluster validation (no formal cluster significance testing).\n\n## Data\n\n| Role | Source |\n|------|--------|\n| Genus taxa | `data/processed/genus.csv` (`make save`) |\n| Diet | `data/processed/dietary_cleaned.xlsx` |\n| Disease group (reference) | `Study_group_new` on mycobiome metadata |\n\n- **Unit of analysis:** **Participant** (one row per `Participant_ID`).\n- **Mycobiome:** Mean genus relative abundance across stool samples per participant.\n- **Diet:** Mean nutrient intake across diary days per participant (same as `merge_files.R`).\n- **Features:** Panel of nutrients from `NUTRIENT_FIELDS` plus all genus columns (`g__*`) with non-zero variance across participants.\n- **Preprocessing:** Features are centered and scaled before PCA and clustering.\n\n\n\n**Coverage:** 12 participants, 51 features (11 nutrients + 40 genera).\n\n## Methods\n\n| Item | Choice |\n|------|--------|\n| Integration | Left-join participant-mean genus abundances and nutrients on `Participant_ID` |\n| PCA | `stats::prcomp`, `center = TRUE`, `scale. = TRUE` |\n| Clustering | Hierarchical (Ward.D2) on Euclidean distance of scaled features |\n| Cluster sizes | k = 2 and k = 3 (`cutree`) |\n| Reference labels | `Study_group_new` overlaid on PCA (not used to fit clusters) |\n| Notebook reference | `notebooks/pca_tsne.Rmd` (taxa-only PCA/t-SNE) |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Results objects created in setup: pca_fit, cluster_fit, scores\n```\n:::\n\n\n## Assumptions and diagnostics\n\n- **Sample size:** 12 participants; PCA axes and clusters are unstable and sensitive to outliers.\n- **Scale:** Nutrients (g, kcal, mg) and compositional genus proportions are jointly z-scored; relative weighting is arbitrary but standard for integrated PCA.\n- **Compositional data:** Genus abundances are not CLR-transformed here; results complement Bray–Curtis / PERMANOVA analyses on taxa alone.\n- **Independence:** Technical stool replicates are averaged before analysis.\n\n## Results\n\n### Variance explained\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|PC   | Component| Variance (%)| Cumulative (%)|\n|:----|---------:|------------:|--------------:|\n|PC1  |         1|        14.78|          14.78|\n|PC2  |         2|        12.96|          27.74|\n|PC3  |         3|        12.53|          40.27|\n|PC4  |         4|        11.59|          51.87|\n|PC5  |         5|        11.19|          63.06|\n|PC6  |         6|         8.84|          71.90|\n|PC7  |         7|         7.30|          79.20|\n|PC8  |         8|         6.97|          86.17|\n|PC9  |         9|         6.00|          92.17|\n|PC10 |        10|         4.89|          97.06|\n\n\n:::\n:::\n\n\nPC1 and PC2 explain **14.8%** and **13.0%** of variance (cumulative PC1–3: **40.3%**).\n\n### Clusters vs study group\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Participant counts: hierarchical clusters (k = 2) vs study group\n\n|cluster | Active IBD| Non-IBD| Quiescent|\n|:-------|----------:|-------:|---------:|\n|1       |          4|       3|         3|\n|2       |          0|       1|         1|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Participant counts: hierarchical clusters (k = 3) vs study group\n\n|cluster | Active IBD| Non-IBD| Quiescent|\n|:-------|----------:|-------:|---------:|\n|1       |          2|       1|         1|\n|2       |          2|       2|         2|\n|3       |          0|       1|         1|\n\n\n:::\n:::\n\n\nClusters are **unsupervised** and need not align with clinical study group. Compare tables and PCA colours to see whether diet–mycobiome structure tracks disease status or forms separate groupings.\n\n## Figures\n\n### Cumulative variance (scree)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_pca_variance(pca_fit$variance_df, max_pc = min(10L, n_participants))\n```\n\n::: {.cell-output-display}\n![Cumulative proportion of variance explained by principal components.](index_files/figure-html/fig-variance-1.png){#fig-variance fig-align='center' width=672}\n:::\n:::\n\n\n### PCA scores (PC1 vs PC2)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_pca_scores(\n  scores,\n  colour_col = \"Study_group_new\",\n  variance_df = pca_fit$variance_df,\n  title = NULL\n)\n```\n\n::: {.cell-output-display}\n![PCA of combined nutrient and genus features. Points are participants; colour is study group.](index_files/figure-html/fig-pca-study-group-1.png){#fig-pca-study-group fig-align='center' width=768}\n:::\n:::\n\n\n### PCA with hierarchical clusters (k = 2)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_pca_scores(\n  scores,\n  colour_col = \"Study_group_new\",\n  shape_col = \"k2\",\n  variance_df = pca_fit$variance_df,\n  title = \"PCA with hierarchical clusters (k = 2)\"\n)\n```\n\n::: {.cell-output-display}\n![Same PCA space with point shape indicating Ward clusters (k = 2).](index_files/figure-html/fig-pca-k2-1.png){#fig-pca-k2 fig-align='center' width=768}\n:::\n:::\n\n\n### Top PC1 loadings\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_top_pca_loadings(pca_fit$loadings, pc = \"PC1\", n_top = 10L)\n```\n\n::: {.cell-output-display}\n![Features with largest absolute loadings on PC1 (nutrients and genera).](index_files/figure-html/fig-loadings-1.png){#fig-loadings fig-align='center' width=672}\n:::\n:::\n\n\n### Clustering dendrogram\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_cluster_dendrogram(cluster_fit)\n```\n\n::: {.cell-output-display}\n![Ward hierarchical clustering dendrogram on scaled diet + genus features (participant IDs as leaves).](index_files/figure-html/fig-dendrogram-1.png){#fig-dendrogram fig-align='center' width=768}\n:::\n:::\n\n\n\n\n## Interpretation\n\nPCA reduces the joint nutrient + genus feature space to orthogonal axes for visualization. If participants with similar diets and mycobiomes sit near each other, they may form visual groups; **formal cluster validity was not assessed** (silhouette, gap statistic, etc.) given small n.\n\nHierarchical clusters partition participants without using `Study_group_new`. Agreement between clusters and clinical group supports an integrated diet–mycobiome signal; disagreement suggests heterogeneity within disease labels or driven by diet/taxa not captured by group alone.\n\n## Reproducibility\n\n- **Helpers:** `stats/R/pca_clustering_helpers.R`, `stats/R/nutrient_association_helpers.R`, `stats/R/permanova_helpers.R`\n- **Notebook:** `notebooks/pca_tsne.Rmd` (taxa-only PCA/t-SNE)\n- **Render:** `quarto render stats` from repository root\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}