{
  "hash": "f282aa3c6b39441aadb5d1e7579d9b56",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Evidence-ranking matrix for disease-group findings\"\ndescription: \"Ranks the strongest diet, mycobiome, and symptom differences across Study_group_new to prioritize candidates for future validation.\"\ndate: 2026-05-29\ncategories: [pre-specified, synthesis, validation]\nauthor: \"IBD Capstone team\"\n---\n\n## Research question\n\nWhich **disease-group** (`Study_group_new`) findings are **strongest candidates for future validation**?\n\nWe synthesize tests already run across the capstone pipeline into a single **evidence-ranking matrix**, ordered by a transparent score combining p-value and effect size.\n\n## Data and inputs\n\n| Domain | Tests included | Primary inputs |\n|--------|----------------|----------------|\n| Mycobiome (beta) | PERMANOVA x taxonomic level | `data/processed/{phylum,family,genus,species}.csv` |\n| Mycobiome (alpha) | Kruskal-Wallis x diversity metric | `data/intermediate/alpha_long.rds` |\n| Diet | Kruskal-Wallis x nutrient | `data/processed/dietary_cleaned.xlsx` + mycobiome metadata |\n| Symptoms | Kruskal-Wallis x symptom score | `data/processed/cleaned_characteristics.csv` + mycobiome metadata |\n\n- **Comparison:** Active IBD vs Quiescent vs Non-IBD (`Study_group_new`).\n- **Unit:** Sample-level for mycobiome; participant-level for diet and symptoms (diet/symptoms joined to mycobiome participants).\n- **Not included here:** Continuous symptom-composition associations (Spearman/PERMANOVA on HBI), stratified nutrient-diversity Spearman, or unsupervised PCA clusters; see linked posts below.\n\n\n\n**Summary:** 24 study-group comparisons ranked; 1 with p < 0.05; 1 tagged **High** priority.\n\n## Methods\n\n| Item | Choice |\n|------|--------|\n| Integration | Recompute or aggregate from processed/intermediate files (same sources as individual posts) |\n| Beta diversity | PERMANOVA (`adonis2`), Bray-Curtis, 999 permutations; effect = R^2 |\n| Alpha, diet, symptoms | Kruskal-Wallis; effect = eta^2[H] (`rstatix::kruskal_effsize`) |\n| Evidence score | `-log10(p) * (0.5 + 0.5 * effect_scaled)` with R^2 or eta^2[H] capped at 1 |\n| Validation tier | **High:** p < 0.05 and score >= 75th percentile among significant; **Medium:** p < 0.05; **Suggestive:** p < 0.10; **Low:** otherwise |\n| Multiplicity | Exploratory ranking; no global FDR across all rows |\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_validation <- ranked |>\n  filter(validation_tier %in% c(\"High\", \"Medium\")) |>\n  slice_head(n = 10)\n```\n:::\n\n\n## Results\n\n### Full evidence-ranking matrix\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Rank|Tier       |Domain                      |Feature                        |Test                    |Effect         | Statistic|      p|  n| Evidence score|Source post                                  |\n|----:|:----------|:---------------------------|:------------------------------|:-----------------------|:--------------|---------:|------:|--:|--------------:|:--------------------------------------------|\n|    1|High       |Symptoms (survey)           |Harvey-Bradshaw Index          |Kruskal–Wallis          |η²[H] = 0.924  |   10.3150| 0.0058| 12|         2.1544|2026-05-22-symptoms-fungal-composition       |\n|    2|Suggestive |Diet (nutrients)            |Added sugar (g/day)            |Kruskal–Wallis          |η²[H] = 0.423  |    5.8077| 0.0548| 12|         0.8974|2026-05-29-nutrients-diversity-disease-group |\n|    3|Suggestive |Mycobiome (beta diversity)  |Species composition            |PERMANOVA (Bray–Curtis) |R² = 0.169     |    1.3205| 0.0880| 16|         0.6169|2026-05-19-permanova-species-beta-diversity  |\n|    4|Low        |Mycobiome (beta diversity)  |Phylum composition             |PERMANOVA (Bray–Curtis) |R² = 0.225     |    1.8871| 0.1260| 16|         0.5510|2026-05-19-permanova-phylum-beta-diversity   |\n|    5|Low        |Mycobiome (alpha diversity) |Shannon diversity              |Kruskal–Wallis          |η²[H] = 0.116  |    3.5103| 0.1730| 16|         0.4252|2026-05-19-alpha-diversity-kruskal-wallis    |\n|    6|Low        |Diet (nutrients)            |Fat (g/day)                    |Kruskal–Wallis          |η²[H] = 0.137  |    3.2308| 0.1990| 12|         0.3985|2026-05-29-nutrients-diversity-disease-group |\n|    7|Low        |Diet (nutrients)            |Vitamin D (mcg/day)            |Kruskal–Wallis          |η²[H] = 0.000  |    2.0000| 0.3680| 12|         0.2171|2026-05-29-nutrients-diversity-disease-group |\n|    8|Low        |Diet (nutrients)            |Sugar (g/day)                  |Kruskal–Wallis          |η²[H] = -0.013 |    1.8846| 0.3900| 12|         0.2045|2026-05-29-nutrients-diversity-disease-group |\n|    9|Low        |Diet (nutrients)            |Omega-6 (g/day)                |Kruskal–Wallis          |η²[H] = -0.013 |    1.8846| 0.3900| 12|         0.2045|2026-05-29-nutrients-diversity-disease-group |\n|   10|Low        |Diet (nutrients)            |Calories (kcal/day)            |Kruskal–Wallis          |η²[H] = -0.056 |    1.5000| 0.4720| 12|         0.1630|2026-05-29-nutrients-diversity-disease-group |\n|   11|Low        |Mycobiome (alpha diversity) |Chao1 diversity                |Kruskal–Wallis          |η²[H] = -0.039 |    1.4941| 0.4740| 16|         0.1621|2026-05-19-alpha-diversity-kruskal-wallis    |\n|   12|Low        |Mycobiome (alpha diversity) |Simpson diversity              |Kruskal–Wallis          |η²[H] = -0.043 |    1.4412| 0.4860| 16|         0.1567|2026-05-19-alpha-diversity-kruskal-wallis    |\n|   13|Low        |Diet (nutrients)            |Folate (mcg/day)               |Kruskal–Wallis          |η²[H] = -0.064 |    1.4231| 0.4910| 12|         0.1545|2026-05-29-nutrients-diversity-disease-group |\n|   14|Low        |Diet (nutrients)            |Artificial sweeteners (mg/day) |Kruskal–Wallis          |η²[H] = -0.090 |    1.1923| 0.5510| 12|         0.1294|2026-05-29-nutrients-diversity-disease-group |\n|   15|Low        |Symptoms (survey)           |Fatigue frequency              |Kruskal–Wallis          |η²[H] = -0.098 |    1.1200| 0.5710| 12|         0.1217|2026-05-22-symptoms-fungal-composition       |\n|   16|Low        |Mycobiome (beta diversity)  |Genus composition              |PERMANOVA (Bray–Curtis) |R² = 0.123     |    0.9116| 0.6800| 16|         0.0940|2026-05-19-permanova-genus-beta-diversity    |\n|   17|Low        |Mycobiome (beta diversity)  |Family composition             |PERMANOVA (Bray–Curtis) |R² = 0.117     |    0.8583| 0.7050| 16|         0.0848|2026-05-19-permanova-family-beta-diversity   |\n|   18|Low        |Symptoms (survey)           |Abdominal pain                 |Kruskal–Wallis          |η²[H] = -0.146 |    0.6875| 0.7090| 12|         0.0747|2026-05-22-symptoms-fungal-composition       |\n|   19|Low        |Diet (nutrients)            |Tryptophan (g/day)             |Kruskal–Wallis          |η²[H] = -0.171 |    0.4615| 0.7940| 12|         0.0501|2026-05-29-nutrients-diversity-disease-group |\n|   20|Low        |Diet (nutrients)            |Omega-3 (g/day)                |Kruskal–Wallis          |η²[H] = -0.192 |    0.2692| 0.8740| 12|         0.0292|2026-05-29-nutrients-diversity-disease-group |\n|   21|Low        |Symptoms (survey)           |Anxiety frequency              |Kruskal–Wallis          |η²[H] = -0.204 |    0.1600| 0.9230| 12|         0.0174|2026-05-22-symptoms-fungal-composition       |\n|   22|Low        |Symptoms (survey)           |Abdominal bloating frequency   |Kruskal–Wallis          |η²[H] = -0.204 |    0.1600| 0.9230| 12|         0.0174|2026-05-22-symptoms-fungal-composition       |\n|   23|Low        |Diet (nutrients)            |Total fiber (g/day)            |Kruskal–Wallis          |η²[H] = -0.205 |    0.1538| 0.9260| 12|         0.0167|2026-05-29-nutrients-diversity-disease-group |\n|   24|Low        |Symptoms (survey)           |Daily soft stools              |Kruskal–Wallis          |η²[H] = -0.222 |    0.0000| 1.0000| 12|         0.0000|2026-05-22-symptoms-fungal-composition       |\n\n\n:::\n:::\n\n\n### Top candidates for future validation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Highest-priority findings (High or Medium tier, top 10 by evidence score)\n\n| rank|validation_tier |domain            |feature               |test           |effect_label  |      p| evidence_score|\n|----:|:---------------|:-----------------|:---------------------|:--------------|:-------------|------:|--------------:|\n|    1|High            |Symptoms (survey) |Harvey-Bradshaw Index |Kruskal–Wallis |η²[H] = 0.924 | 0.0058|         2.1544|\n\n\n:::\n:::\n\n\n**Top validation candidates:**\n\n1. [High] **Symptoms (survey)** - Harvey-Bradshaw Index (η²[H] = 0.924; Kruskal–Wallis, p = 0.0058, score = 2.15)\n\n### By domain (mean evidence score)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Domain                      | Tests| p < 0.05| Mean evidence score|Top feature           |\n|:---------------------------|-----:|--------:|-------------------:|:---------------------|\n|Diet (nutrients)            |    11|        0|               0.224|Added sugar (g/day)   |\n|Mycobiome (alpha diversity) |     3|        0|               0.248|Shannon diversity     |\n|Mycobiome (beta diversity)  |     4|        0|               0.337|Species composition   |\n|Symptoms (survey)           |     6|        1|               0.398|Harvey-Bradshaw Index |\n\n\n:::\n:::\n\n\n## Figure\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_evidence_heatmap(ranked, top_n = min(20L, nrow(ranked)))\n```\n\n::: {.cell-output-display}\n![Evidence scores for the top 20 study-group comparisons. Higher scores indicate stronger statistical support for validation.](index_files/figure-html/fig-evidence-heatmap-1.png){#fig-evidence-heatmap fig-align='center' width=864}\n:::\n:::\n\n\n\n\n## Interpretation\n\nThe matrix **does not replace** individual analysis posts; it prioritizes which disease-group contrasts to carry forward (e.g. pre-registration, larger cohort, or experimental follow-up).\n\n**High** tier findings combine statistical significance with relatively large R^2 (composition) or eta^2[H] (rank-based outcomes). **Low** tier rows may still be biologically interesting but need replication. Domains with few participants (especially diet and symptoms) should be interpreted cautiously.\n\n### Related analyses (not in this matrix)\n\n| Topic | Post |\n|-------|------|\n| Symptom x diversity (Spearman, HBI PERMANOVA) | `2026-05-22-symptoms-fungal-composition` |\n| Nutrient x diversity (stratified Spearman) | `2026-05-29-nutrients-diversity-disease-group` |\n| Diet + mycobiome PCA / clustering | `2026-05-29-diet-mycobiome-pca-clustering` |\n\n## Reproducibility\n\n- **Helpers:** `stats/R/evidence_ranking_helpers.R`\n- **Render:** `quarto render stats` from repository root\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}