{
  "hash": "8ce62504567eccbf2b57c5e1fb2555a1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Symptom scores vs fungal composition (Spearman and PERMANOVA)\"\ndescription: \"Survey symptom scores (HBI and related items) tested against alpha diversity (Spearman) and genus beta diversity (PERMANOVA on Bray–Curtis).\"\ndate: 2026-05-22\ncategories: [pre-specified, alpha-diversity, beta-diversity, genus, symptoms]\nauthor: \"IBD Capstone team\"\n---\n\n## Research question\n\nAre **symptom scores** from participant surveys associated with **fungal composition** (alpha and beta diversity)?\n\n**Null (Spearman):** No monotonic association between each symptom score and each alpha diversity metric.\n\n**Null (PERMANOVA):** Genus-level community composition is not associated with the symptom score after accounting for Bray–Curtis distance structure.\n\n## Data\n\n| Role | Source |\n|------|--------|\n| Mycobiome (alpha) | `data/intermediate/alpha_long.rds` (`make wrangle`) |\n| Mycobiome (genus beta) | `data/processed/genus.csv` (`make save`) |\n| Survey / symptoms | `data/processed/cleaned_characteristics.csv` (`make characteristics` on `data/raw/OPT_Participant Characteristics(Sheet1).csv`) |\n\n- **Unit of analysis:** Stool sample (22 samples, 12 participants with mycobiome data).\n- **Join key:** `Participant_ID` (mycobiome) = `participant_id` (characteristics); one characteristics row per participant used when duplicates exist.\n- **Symptom scores:** Numeric fields and ordinally coded items parsed to numbers (e.g. `Mild = 1`, `4\\tSOME OF THE TIME` → 4). Primary focus: **Harvey–Bradshaw Index (HBI)**; additional exploratory symptoms in the correlation table.\n- **Inclusion:** Samples retained after `02_data_wrangling.R` removals; PERMANOVA genus analysis uses samples with non-missing HBI.\n\n\n\n**Coverage:** 16 samples, 12 participants; 16 samples with non-missing HBI.\n\n## Methods\n\n| Item | Spearman (symptoms × alpha) | PERMANOVA (symptoms × taxa) |\n|------|----------------------------|-----------------------------|\n| Test | Spearman rank correlation (`cor.test`, `method = \"spearman\"`) | `vegan::adonis2` |\n| Response | Shannon, Simpson, Chao1 | Genus Bray–Curtis dissimilarity |\n| Predictor | Parsed symptom scores | Harvey–Bradshaw Index (continuous) |\n| Multiple testing | Benjamini–Hochberg across all symptom × metric pairs | Exploratory single predictor |\n| Permutations | — | 999 |\n| Significance | α = 0.05 | α = 0.05 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspearman_results <- spearman_symptom_alpha(sample_symptoms)\n\npermanova_hbi <- run_permanova_symptom(\n  genus_wide,\n  prefix = TAXA_LEVELS$genus$prefix,\n  symptom_col = \"harvey_bradshaw_index\"\n)\n```\n:::\n\n\n## Assumptions and diagnostics\n\n- **Independence:** Samples are not fully independent (up to two stool replicates per participant). Results are exploratory; consider participant-level sensitivity analyses if reporting formally.\n- **Spearman:** Tests monotonic association; does not assume linearity or normality.\n- **PERMANOVA:** Exchangeability under permutations; composition constrained to genus relative abundance (Bray–Curtis).\n- **Missing symptoms:** HBI and other scores are not available for all participants (see coverage above).\n\n## Results\n\n### Spearman: symptom scores × alpha diversity\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Symptom                      |Alpha metric |  n| Spearman rho|      p| BH-adjusted p|\n|:----------------------------|:------------|--:|------------:|------:|-------------:|\n|Harvey-Bradshaw Index        |Shannon      | 16|      -0.4543| 0.0771|        0.6620|\n|Harvey-Bradshaw Index        |Simpson      | 16|       0.2331| 0.3849|        0.7339|\n|Harvey-Bradshaw Index        |Chao1        | 16|       0.3595| 0.1715|        0.6620|\n|Daily soft stools            |Shannon      | 16|       0.2205| 0.4118|        0.7339|\n|Daily soft stools            |Simpson      | 16|      -0.0214| 0.9372|        0.9406|\n|Daily soft stools            |Chao1        | 16|      -0.2757| 0.3014|        0.6782|\n|Abdominal pain               |Shannon      | 16|      -0.3009| 0.2574|        0.6620|\n|Abdominal pain               |Simpson      | 16|      -0.0203| 0.9406|        0.9406|\n|Abdominal pain               |Chao1        | 16|      -0.0483| 0.8589|        0.9406|\n|Fatigue frequency            |Shannon      | 16|       0.3156| 0.2337|        0.6620|\n|Fatigue frequency            |Simpson      | 16|      -0.1593| 0.5556|        0.7339|\n|Fatigue frequency            |Chao1        | 16|      -0.1683| 0.5332|        0.7339|\n|Anxiety frequency            |Shannon      | 16|      -0.0932| 0.7314|        0.8777|\n|Anxiety frequency            |Simpson      | 16|       0.1533| 0.5708|        0.7339|\n|Anxiety frequency            |Chao1        | 16|      -0.3367| 0.2023|        0.6620|\n|Abdominal bloating frequency |Shannon      | 16|      -0.1894| 0.4824|        0.7339|\n|Abdominal bloating frequency |Simpson      | 16|      -0.3277| 0.2154|        0.6620|\n|Abdominal bloating frequency |Chao1        | 16|       0.3848| 0.1411|        0.6620|\n\n\n:::\n:::\n\n\n**No symptom × alpha pairs were significant after BH adjustment (q < 0.05).**\n\n### PERMANOVA: genus composition ~ HBI\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Term     | Df| Sum of squares|     R²|      F| Pr(>F)|\n|:--------|--:|--------------:|------:|------:|------:|\n|Model    |  1|         0.0995| 0.0563| 0.8357|  0.722|\n|Residual | 14|         1.6677| 0.9437|     NA|     NA|\n|Total    | 15|         1.7673| 1.0000|     NA|     NA|\n\n\n:::\n:::\n\n\n**Harvey–Bradshaw Index** explained **5.6%** of variance in genus composition (R² = 0.056; pseudo-F = 0.84; p = 0.7220, 999 permutations; n = 16 samples with HBI).\n\n## Figures\n\n### HBI vs Shannon diversity (Spearman)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_symptom_alpha_scatter(\n  sample_symptoms,\n  symptom_col = \"harvey_bradshaw_index\",\n  metric = \"Shannon\"\n)\n```\n\n::: {.cell-output-display}\n![Harvey–Bradshaw Index vs Shannon diversity by study group. Subtitle shows Spearman correlation across samples with complete data.](index_files/figure-html/fig-hbi-shannon-1.png){#fig-hbi-shannon fig-align='center' width=672}\n:::\n:::\n\n\n### Genus PCoA coloured by HBI (PERMANOVA)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_pcoa_symptom(\n  permanova_hbi,\n  TAXA_LEVELS$genus$label\n)\n```\n\n::: {.cell-output-display}\n![PCoA of genus Bray–Curtis dissimilarity; points coloured by Harvey–Bradshaw Index.](index_files/figure-html/fig-pcoa-hbi-1.png){#fig-pcoa-hbi fig-align='center' width=672}\n:::\n:::\n\n\n\n\n## Interpretation\n\nSpearman correlations describe **pairwise monotonic links** between symptom scores and alpha metrics at the sample level; they do not adjust for repeated measures per participant. PERMANOVA tests whether **multivariate genus composition** covaries with HBI across samples; a non-significant p-value does not rule out associations with individual taxa or other symptom instruments.\n\nCorrelation among symptoms and small sample size limit power; treat findings as **exploratory** unless pre-registered.\n\n## Reproducibility\n\n- **Helpers:** `stats/R/symptom_association_helpers.R`, `stats/R/permanova_helpers.R`\n- **Optional merged table:** `make merge` builds `data/processed/merged.csv` for dashboard use; this post joins the same sources directly.\n- **Render:** `quarto render stats` from repository root\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}