project:
  type: website
  output-dir: _site

website:
  title: "MDS Capstone Project"
  description: "Methods, results, and figures for pre-specified and exploratory analyses"
  site-url: "https://charming-pie-62264d.netlify.app/"
  repo-url: "https://github.com/farkasvic/BCCHR_IBD_Capstone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Exploratory Analysis
      - href: pre-specified.qmd
        text: Pre-specified Tests
      - href: _template.qmd
        text: New Analysis Template
    right:
      - icon: github
        href: "https://github.com/farkasvic/BCCHR_IBD_Capstone"
        aria-label: GitHub

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Show code"
    fig-cap-location: bottom
    embed-resources: false

execute:
  freeze: auto
  warning: false
  message: false
