# 00_functions.R
# Shared helpers used by the dietary exploratory plots in `src/diet`.
# These functions centralize file paths, input loading, and small reusable
# transformations so the figure scripts stay short and consistent.

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(readr)
  library(readxl)
  library(tidyr)
})

source("src/participant_id.R")

#
# Build a path under `data/processed` for dietary inputs that have already been
# cleaned or merged elsewhere in the project.
diet_processed_path <- function(...) {
  file.path("data", "processed", ...)
}

#
# Build a path under `data/intermediate` for diet-specific artifacts created
# during the EDA workflow.
diet_intermediate_path <- function(...) {
  file.path("data", "intermediate", ...)
}

#
# Build a path under `figures/diet` for exported dietary figures.
diet_figure_path <- function(...) {
  file.path("figures", "diet", ...)
}

#
# Ensure directories required by the dietary EDA workflow exist before writing
# any intermediate files or figures.
ensure_diet_dirs <- function() {
  dir.create(diet_intermediate_path(), recursive = TRUE, showWarnings = FALSE)
  dir.create(diet_figure_path(), recursive = TRUE, showWarnings = FALSE)
}

#
# Load the cleaned dietary workbook generated by `src/diet/dietary.R`.
# Returns the `Data` sheet used by the downstream EDA scripts.
load_dietary_cleaned <- function() {
  readxl::read_excel(diet_processed_path("dietary_cleaned.xlsx"), sheet = "Data")
}

#
# Load the processed merged metadata table produced by the wider project
# wrangling pipeline.
load_merged_processed <- function() {
  readr::read_csv(diet_processed_path("merged.csv"), show_col_types = FALSE)
}

#
# Load study-group metadata used to stratify dietary figures.
# The function prefers an intermediate RDS if one exists, then falls back to the
# merged processed CSV. This keeps the plotting scripts decoupled from the exact
# upstream storage format.
load_mycobiome_meta <- function() {
  meta_rds <- diet_intermediate_path("meta_data.rds")
  merged_csv <- diet_processed_path("merged.csv")

  if (file.exists(meta_rds)) {
    return(readRDS(meta_rds))
  }

  if (file.exists(merged_csv)) {
    merged <- load_merged_processed()
    return(
      merged |>
        transmute(
          Participant_ID = Participant_ID,
          Study_group_new = Study_group_new,
          Fiber_restriction = Fiber_restriction
        ) |>
        distinct()
    )
  }

  stop(
    "Missing metadata input for dietary EDA. Run `make wrangle` or generate ",
    "`data/processed/merged.csv` first.",
    call. = FALSE
  )
}

#
# Save a ggplot object into the diet figure directory using consistent defaults.
save_diet_plot <- function(plot, filename, width = 12, height = 8, dpi = 300) {
  ensure_diet_dirs()
  ggplot2::ggsave(
    filename = diet_figure_path(filename),
    plot = plot,
    width = width,
    height = height,
    dpi = dpi
  )
}

#
# Identify numeric dietary columns beginning at `start_col`.
# By default, derived quartile columns are excluded because most plots should
# operate on the original continuous measurements.
get_diet_numeric_cols <- function(df, start_col = 4, exclude_quartiles = TRUE, extra_exclude = character()) {
  if (ncol(df) < start_col) {
    return(character(0))
  }

  candidate_cols <- names(df)[seq.int(start_col, ncol(df))]
  candidate_cols <- candidate_cols[candidate_cols %in% names(df)]
  numeric_cols <- candidate_cols[vapply(df[, candidate_cols, drop = FALSE], is.numeric, logical(1))]

  if (exclude_quartiles) {
    numeric_cols <- numeric_cols[!grepl("_quartile$", numeric_cols)]
  }

  numeric_cols[!numeric_cols %in% extra_exclude]
}

#
# Rescale a numeric vector to the [0, 1] interval when possible.
# Constant or non-finite vectors are returned unchanged to avoid creating
# misleading values or errors in plotting code.
rescale_minmax <- function(x) {
  if (all(is.na(x))) {
    return(rep(NA_real_, length(x)))
  }

  x_num <- as.numeric(x)
  min_x <- min(x_num, na.rm = TRUE)
  max_x <- max(x_num, na.rm = TRUE)
  if (!is.finite(min_x) || !is.finite(max_x) || identical(min_x, max_x)) {
    return(x_num)
  }

  (x_num - min_x) / (max_x - min_x)
}

# Dietary guideline targets used by `05_deficiency_barplot.R` to summarize how
# far participant-level averages fall below selected food-group recommendations.
cfg_targets <- c(
  "MPGrain (oz-eq)" = 6,
  "MPVeg (c-eq)" = 2.5,
  "MPFruit (c-eq)" = 2,
  "MPDairy (c-eq)" = 3,
  "MPProt (oz-eq)" = 5.5
)
